export const ACTIONS = {
	GET_APPLICATIONS: 'GET_APPLICATIONS',
	GET_TYPES: 'GET_TYPES',
	SET_APPLICATIONS: 'SET_APPLICATIONS',
	SET_SELECTED_APPLICATION: 'SET_SELECTED_APPLICATION',
	SET_TYPES: 'SET_TYPES'
};
